name: 'Maintain Revision'
description: 'Keep a remote development version number up to date for a project'
author: 'Antti Kivi'
inputs:
  type:
    description: 'The type of the file that contains the version of the project, possible values are npm, json, and txt'
    required: true
    default: 'npm'
  file:
    description: 'Relative path to the file that contains the version of the project'
    required: false
  bucket:
    description: 'The AWS S3 bucket where the remove development version is held'
    required: true
    default: 'anthem-workflows'
  path:
    description: 'Path to the directory where the version file is'
    required: false
  upload:
    description: 'Whether or not the next development version will be uploaded to S3'
    required: true
    default: true
  release:
    description: 'Whether or not check the version number for release, which means that the remote version is not read nor uploaded'
    required: false
    default: false
outputs:
  version:
    description: 'The full version number of the current build'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/upload/index.js'
  post-if: 'success()'
branding:
  icon: 'tag'
  color: 'blue'
