name: 'Maintain Revision'
description: 'Keep a remote development version number up to date for a project'
author: 'Visiosto oy'
inputs:
  type:
    description: 'The type of the file that contains the version of the project, possible values are npm, json, python, and txt.'
    required: true
    default: 'npm'
  file:
    description: 'Relative path to the file that contains the version of the project.'
    required: false
  storage:
    description: 'The storage service that holds the bucket and remove revision files. The only possible value currently is s3.'
    required: true
    default: 's3'
  bucket:
    description: 'The name of the AWS S3 bucket where the remove development version is held.'
    required: true
  path:
    description: 'Path in the S3 bucket to the directory where the remote version file is.'
    required: false
  download:
    description: 'Whether or not the file which contains the version number for this build should be downloaded from S3 for this build. If this is not set to true and the revision is not given manually, the replacement is not done.'
    required: true
    default: true
  upload:
    description: 'Whether or not the file which contains the next number for the next development version should be uploaded to S3 so that the next build can use it.'
    required: true
    default: true
outputs:
  version:
    description: 'The full version number of the current build.'
  revision-number:
    description: 'The revision number used in this run.'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/upload/index.js'
  post-if: 'success()'
branding:
  icon: 'tag'
  color: 'blue'
