name: 'Maintain revision'
description: 'Keep a remote development version number up to date for a project'
author: 'Antti Kivi'
inputs:
  bucket:
    required: true
    description: 'The AWS S3 bucket where the remove development version is held'
    default: 'anthem-workflows'
  path:
    required: false
    description: 'Path to the directory where the version file is'
outputs:
  version:
    description: 'The full version number of the current build'
runs:
  using: 'node12'
  main: 'dist/index.js'
